In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
np.append(a, [7,8,9])

array([1, 2, 3, 4, 5, 7, 8, 9])

In [6]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
np.append(a, [[5,6]])

array([1, 2, 3, 4, 5, 6])

In [9]:
np.append(a, [[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
a = np.append(a, [[5,6]], axis=0)
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 6]])

In [14]:
np.delete(a, 2, 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 6]])

In [16]:
np.delete(a, 0, 0)

array([[3, 4],
       [5, 6],
       [5, 6]])

In [17]:
np.delete(a, 0, 1)

array([[2],
       [4],
       [6],
       [6]])

In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
np.delete(a, np.s_[::2], 0)

array([[ 4,  5,  6],
       [10, 11, 12]])

In [29]:
np.delete(a, np.s_[:2:], 1)

array([[ 3],
       [ 6],
       [ 9],
       [12]])