<a href="https://colab.research.google.com/github/GabrielIFPB/data_science/blob/gabriel/numpy/divisao_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array_split(a, 2, axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [5]:
np.array_split(a, 2, axis=1)

[array([[1, 2],
        [4, 5]]), array([[3],
        [6]])]

In [6]:
b = np.array([[12,11,10,],[9,8,7],[6,5,4],[3,2,1]])
b

array([[12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [9]:
arrays = np.array_split(b, 2, axis=0)
for array in arrays:
  print(array)

[[12 11 10]
 [ 9  8  7]]
[[6 5 4]
 [3 2 1]]


In [10]:
arrays = np.array_split(b, 2, axis=1)
for array in arrays:
  print(array)

[[12 11]
 [ 9  8]
 [ 6  5]
 [ 3  2]]
[[10]
 [ 7]
 [ 4]
 [ 1]]
