<a href="https://colab.research.google.com/github/GabrielIFPB/data_science/blob/gabriel/numpy/indexacao_booleana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
a[a > 3]

array([4, 5, 6])

In [4]:
a[a > 1]

array([2, 3, 4, 5, 6])

In [6]:
idx = (a > 2)
idx

array([[False, False],
       [ True,  True],
       [ True,  True]])