<a href="https://colab.research.google.com/github/GabrielIFPB/data_science/blob/gabriel/numpy/Juntando_uma_sequ%C3%AAncia_de_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print(a)
print()
print(b)

[[1 2]
 [3 4]]

[[5 6]]


In [4]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
# np.concatenate((a, b), axis=1)
b.T

array([[5],
       [6]])

In [7]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])