In [6]:
import numpy as np

In [9]:
a = np.array([10, 20, 30, 40])

In [10]:
type(a)

numpy.ndarray

In [11]:
mat = np.array([[1,2],[3,4]])
print(mat)
print(mat[1][1])
print(mat[-1][-1])
print(mat[1,:])
print(mat[:,0])

[[1 2]
 [3 4]]
4
4
[3 4]
[1 3]


In [12]:
mat.transpose()

array([[1, 3],
       [2, 4]])

In [20]:
a = np.array([[2,4],[6,8]])
a.

In [25]:
joao_pts = [20,30,40,15]
pedro_pts = [100,24,48,23]
maria_pts = [92,22,34,12]
marcos_pts = [12,34,12,43]

pontos = np.array([joao_pts,pedro_pts,maria_pts,marcos_pts])
pontos

array([[ 20,  30,  40,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  34,  12,  43]])

In [27]:
pontos[0]

array([20, 30, 40, 15])

In [28]:
pontos[1][0]

100

In [30]:
data = np.arange(0, 20)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
mat1 = np.reshape(data,(5,4))
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
mat1[2][2]

10

In [33]:
pontos

array([[ 20,  30,  40,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  34,  12,  43]])

In [34]:
pontos.item(5)

24

In [37]:
m1 = ['python', 'eh', 'legal']
m2 = ['guido', 'van', 'rossum']
m3 = [10,20,30]

In [38]:
[m1,m2,m3]

[['python', 'eh', 'legal'], ['guido', 'van', 'rossum'], [10, 20, 30]]

In [40]:
np.array([m1,m2,m3])

array([['python', 'eh', 'legal'],
       ['guido', 'van', 'rossum'],
       ['10', '20', '30']], dtype='<U6')

In [41]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8,9],[10,11,12]])

In [42]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [46]:
m2 / m1

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [47]:
m2 // m1

array([[7, 4, 3],
       [2, 2, 2]])

In [48]:
np.matrix.round(m2 / m1)

array([[7., 4., 3.],
       [2., 2., 2.]])

In [49]:
10 * m2

array([[ 70,  80,  90],
       [100, 110, 120]])

In [50]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
m1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [54]:
m2 - 1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
m1 * m2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [56]:
m1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])