<a href="https://colab.research.google.com/github/GabrielIFPB/data_science/blob/gabriel/numpy/numpy02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [6]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [5]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [8]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [9]:
np.repeat(a, 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [10]:
np.repeat(a, 3, axis=0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [11]:
np.repeat(a, 2, axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [12]:
np.repeat(a, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [13]:
np.repeat(3, 4)

array([3, 3, 3, 3])

In [14]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
np.tile(a, 2)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [16]:
np.tile(a, 3)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [17]:
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [18]:
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [19]:
np.tile(b, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])