<a href="https://colab.research.google.com/github/GabrielIFPB/data_science/blob/gabriel/numpy/trabalhando_com_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.random.shuffle(a)
a

array([7, 6, 0, 5, 1, 8, 4, 9, 3, 2])

# Números complexos

In [10]:
a = np.array([1, 10 + 2j, 20 + 5j], dtype='complex')
a

array([ 1.+0.j, 10.+2.j, 20.+5.j])

In [12]:
for i in a:
  print(i)

(1+0j)
(10+2j)
(20+5j)


In [13]:
a[1] + a[2]

(30+7j)

In [14]:
a[1] - a[2]

(-10-3j)

In [15]:
a[1] * a[2]

(190+90j)

In [16]:
a[1] / a[2]

(0.49411764705882355-0.023529411764705882j)

In [17]:
a[1] // a[2]

0j

In [18]:
a[2] // a[1]

(2+0j)

In [19]:
a[2] / a[1]

(2.019230769230769+0.09615384615384615j)

# Gerando arrays com linspace

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [22]:
np.linspace(2.0, 3.0, 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [23]:
np.linspace(2.0, 2.5, 5)

array([2.   , 2.125, 2.25 , 2.375, 2.5  ])

# Encontrando elementos únicos de um array

In [24]:
a = np.array([[1, 2], [2, 3 ], [3, 3], [4, 4]])
a

array([[1, 2],
       [2, 3],
       [3, 3],
       [4, 4]])

In [25]:
np.unique(a)

array([1, 2, 3, 4])

# Lendo arquivos CSV com NumPy

In [28]:
valores = np.genfromtxt('arquivo.csv', delimiter=',', skip_header=1)
valores

ValueError: ignored